work_dir: /data/wangkun/project/work_dir/SensorsHAR/UCI/sensorclrv1-seed-1/features
weights: /data/wangkun/project/work_dir/SensorsHAR_0415/UCI/sensorclrv1-seed-1/epoch500_model.pt
phase: 'extract_feature'

# feeder
feeder: feeder.feeder.Feeder_CL
pretrain_feeder_args:
  data_dir: '/data/wangkun/project/datasets/UCI_data/dataset/'
  dataset: 'UCI'
  mode: train
  seq_len: 128
  cl_data: True
  aug: 'PR'
  e_aug: 'PRJS'
  seg: True

train_feeder_args:
  data_dir: '/data/wangkun/project/datasets/UCI_data/dataset/'
  dataset: 'UCI'
  mode: train
  seq_len: 128

test_feeder_args:
  data_dir: '/data/wangkun/project/datasets/UCI_data/dataset/'
  dataset: 'UCI'
  mode: test
  seq_len: 128


# model
model: net.SensorCLR.SensorCLRv1
model_args:
  base_encoder: net.SensorCNN.CNN
  num_classes: 6
  queue_size: 32768
#  queue_size: 5120
  nnm_topk: 1

weight_decay: 0.0001
base_lr: 0.1
optimizer: 'SGD'
lr_decay_type: 'cosine'
end_cosine_lr: 0.0001
device: [0]
batch_size: 512
test_batch_size: 512
num_epoch: 500
pretrain_epoch: 300
#num_epoch: 200
#pretrain_epoch: 0
warmup_epoch: 10
seed: 1
eval_interval: 100
save_interval: 100
bool_save_model: False
bool_save_checkpoint: False
#nnm_epoch: 150
nnm_epoch: 300